### ISSUE TITLE
'regexp jumphub' 

### ISSUE THREAD

**Issue by cSep** [Slamsneider/SingleTom#4]
Thank you. Killer-App alert!  Add a user configurable throttleable 'regexp jumphub' to enable prompt-swapping and javascript calls/loders/generators and you might actually bring about the singularity! Congratulation! tyvm.

**Comment by Slamsneider** [comment]
You are very welcome to fork the repo and make it happen.

Keep me updated ;*)

**Comment by Slamsneider** [comment]
Looks nice.
Could you explain the use of "QUICKPROMPT", I am trying to get my head around its use.

**Comment by marioseixas** [comment]
> Looks nice. Could you explain the use of "QUICKPROMPT", I am trying to get my head around its use.

Section 4: Quick Command Function
The `quickCommand()` function is used to execute quick commands. It takes a parameter `quick`, which is a string representing the quick command to be executed. The function reads various input values from the webpage (e.g., model, quicksource, history) and performs an API request using the `doSend` function. If an error occurs during the API request, an error message is displayed.

**Comment by cSep** [comment]
enter | expand | review | translate into x-language | summarize | organize and bulletize | and the rest of the 50000 things you would otherwise write by hand and apply to transform the output when you're doing something on the fly.

**Comment by marioseixas** [comment]
> 

fucking awesome

**Comment by marioseixas** [comment]
> enter | expand | review | translate into x-language | summarize | organize and bulletize | and the rest of the 50000 things you would otherwise write by hand and apply to transform the output when you're doing something on the fly.

fucking awesome

**Comment by Slamsneider** [comment]
Sounds great, but I'm still not sure how to, and for what "quickCommand" is used. - Would you mind giving an example? (I'm slow today).
