### ISSUE TITLE
could you provide the SingleTom customization that you use?

### ISSUE THREAD

**Issue by marioseixas** [Slamsneider/SingleTom#5]
I want to see how you customized SingleTom for your everyday-use

**Comment by Slamsneider** [comment]
I do not have anything special in my 'customized' version. Atm. I'm more working on a multimodal version that will use a local server. - Have you added some new functionality?

**Comment by marioseixas** [comment]
no, not yet, but I will

but I've tested several, really lots of (check my starred repos), openAI APIs interfaces and SingleTom is really something different.

Another one that I liked very much but the dev abandoned is https://github.com/rikhuijzer/ata

Congratz for your awesome work
